project:
  type: website
  render:
    - "*.qmd"
  resources:
    - "files/"
    - "projects/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "Building Spatial Data"
  site-url: "https://elipousson.github.io/bldgspatialdata"
  description: "Use R and QGIS to understand, modify, and create spatial data about the places we work and live."

  # favicon: "/files/icon-512.png"

  twitter-card:
    image: "/files/img/ges600-logo.png"
    card-style: summary_large_image
    creator: "@elipousson"

  open-graph:
    image: "/files/img/ges600-logo.png"
    locale: en_US

  navbar:
    pinned: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Schedule"
        href: schedule.qmd
      # - text: "Assignments"
      #   file: assignments/index.qmd
      # - text: "Examples"
      #   file: examples/index.qmd
      - text: "Resources"
        file: resources/index.qmd

  page-footer:
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

bibliography: files/references.bib
# csl: chicago-author-date.csl

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    df-print: tibble
    code-link: true
    code-tools: true
    error: true
    highlight-style: a11y
    citeproc: true

editor: visual


