---
title: "Using QGIS"
---

## **About QGIS 📋**

-   Read the [Desktop User Guide/Manual](https://docs.qgis.org/3.22/en/docs/user_manual)

-   Follow the tutorials in the [QGIS Training manual](https://docs.qgis.org/3.22/en/docs/training_manual/)

-   Learn GIS basics in [A gentle introduction in GIS](https://docs.qgis.org/3.22/en/docs/gentle_gis_introduction)

## **Introductory resources 🐣**

-   Explore [QGIS Tutorials and Tips](https://www.qgistutorials.com/en/index.html) from Ujaval Gandhi
-   [Introduction to QGIS](https://spatialthoughts.com/courses/introduction-to-qgis/) from Spatial Thoughts (Ujaval Gandhi)

## **Getting help with QGIS 🆘**

-   Ask [qgis Questions on StackOverflow](https://stackoverflow.com/tags/qgis)

## **Recommended QGIS plugins 🔌**

Plugins are optional for working with spatial data in QGIS but recommended for ease of use and convenience. Plugins are written and published by individual volunteers, government agencies, and private GIS consulting firms. The following table lists a selection of recommended plugins you may want to install.

| **Plugin**                                                                                                                                                             | **Source**                                                         |
|---------------------------------------------------|---------------------|
| [QuickMapServices](https://qms.nextgis.com/) by [NextGIS](https://nextgis.com/)                                                                                        | [repo](https://github.com/nextgis/quickmapservices)                |
| [QGIS Resource Sharing](https://plugins.qgis.org/plugins/qgis_resource_sharing/) by Akbar Gumbira, Håvard Tveite, and Julien Moura                                     | [repo](https://github.com/QGIS-Contribution/QGIS-ResourceSharing/) |
| [qgis2web](https://github.com/tomchadwin/qgis2web) by [Tom Chadwin](https://tom.chadw.in/)                                                                             | [repo](https://github.com/tomchadwin/qgis2web)                     |
| [Processing R Provider](https://north-road.github.io/qgis-processing-r/) by [North Road](https://twitter.com/northroadgeo) and [Jan Caha](https://twitter.com/cahik13) | [repo](https://github.com/north-road/qgis-processing-r)            |

::: callout-tip
Learn more about [installing QGIS plugins](https://docs.qgis.org/3.4/en/docs/training_manual/qgis_plugins/fetching_plugins.html) or writing your own [QGIS Processing plugin](https://www.qgistutorials.com/en/docs/3/building_a_python_plugin.html) (recommended for beginners) or [QGIS Python plugin](https://www.qgistutorials.com/en/docs/3/processing_python_plugin.html) (recommended for advanced users).
:::

## Additional resources

There are a variety of helpful tutorial videos on YouTube covering both introductory and moree advanced topics.

### Introductory

-   [QGIS Uncovered](https://www.youtube.com/playlist?list=PL7HotvlLKHCs9nD1fFUjSOsZrsnctyV2R) by Steven Bernard (a design editor with the Financial Times): These videos are a few years old but they are short and lessons 4, 9, and 10 cover the information you need for the QGIS map making assignment in an accessible format.
-   [An Introductory QGIS Workshop for Beginners](https://youtu.be/-7v5qfJYWxA) from Michele Tobias (UC Davis DataLab): This recorded workshop is over 3 hours long but you may find it helpful to check out the section on mapping vector data (starting at [1:24:00](https://youtu.be/-7v5qfJYWxA?t=5040)) and the section on working with the map layout tools (starting at [2:30:00](https://youtu.be/-7v5qfJYWxA?t=9000)). There is also a [corresponding GitHub repository](https://github.com/ucdavisdatalab/Intro-to-Desktop-GIS-with-QGIS) with more resources.

### Advanced

- [QGIS expressions, variables, data defined settings: putting it all together!](https://youtu.be/h-mpUkwDdOQ) (1 hr 21 min) by Nyall Dawson from the GIS consulting firm North Road. The demonstration of how to use expressions to set labels, colors, symbology and more shows off some of the similarities between QGIS and ggplot2 (or tmap) and illustrates why a desktop GIS application is still a preferred tool for cartography for many folks (even if R excels at the data manipulation and analysis tasks).
-   [A Tour of QGIS Processing Toolbox Algorithms](https://youtu.be/Tkqj3VCxrqI) (22 min) by Ujaval Gandhi (Spatial Thoughts) offers live demonstrations of over 15 different tools within QGIS including spatial joins, importing geotagged photos, converting points to a path, and more.
-   [Session recordings](https://wiki.osgeo.org/wiki/TIB) from the FOSS4G and FOSSGIS Conferences include a number of sessions on using QGIS for research, analysis, and visualization.
